version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - DB_USER=postgres
      - DB_HOST=db
      - DB_NAME=Interno
      - DB_PASSWORD=123
      - DB_PORT=5432
      - JWT_SECRET=sua_chave_secreta
    depends_on:
      - db
    volumes:
      - ./backend:/app
    command: ["npm", "start"]

  db:
    image: postgis/postgis:17-3.4
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=Interno
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata:
